'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.flat",function(a){return a?a:function(b){b=void 0===b?1:b;for(var c=[],d=0;d<this.length;d++){var e=this[d];Array.isArray(e)&&0<b?(e=Array.prototype.flat.call(e,b-1),c.push.apply(c,e)):c.push(e)}return c}},"es9","es5");
var canvas=document.getElementById("previewCanvas"),ctx=canvas.getContext("2d"),qrResult=document.getElementById("qrResult"),inputURL=document.getElementById("inputURL"),loadUrlBtn=document.getElementById("loadUrlBtn"),inputFile=document.getElementById("inputFile"),camScanBtn=document.getElementById("camScan"),pipBtn=document.getElementById("pipBtn"),previewVideo=document.getElementById("previewVideo"),cameraStream,copyBtn=document.getElementById("copy"),openBtn=document.getElementById("launch"),
copiedTimeout,copied=document.getElementById("copied"),containerUrlinput=document.getElementById("container-urlinput"),containerFileinput=document.getElementById("container-fileinput");function initMsg(){let a=document.querySelectorAll("[data-i18n]");for(const b of a)b.textContent=chrome.i18n.getMessage(b.dataset.i18n)}
function requestPermission(a){const b={origins:[a]};chrome.permissions.contains(b,function(c){c?window.alert(chrome.i18n.getMessage("scanLoadError")):chrome.permissions.request(b,function(d){chrome.runtime.lastError?console.log("Error: "+chrome.runtime.lastError.message):d?loadImage():console.log("user denied permission")})})}function uintToString(a){return(new TextDecoder).decode(a)}var quircDecoded,quircResult;
function decoded(a,b,c,d,e,f,g){quircDecoded=!0;a=new Uint8Array(Module.HEAPU8.buffer,f,g);quircResult=uintToString(a)}
function scanImage(a){try{var b=jsQR(a.data,a.width,a.height);if(b&&b.data)return{success:!0,data:b.data}}catch(d){}try{let d=Module._xsetup(a.width,a.height);const e=a.data;for(var c=b=0;b<e.length;b+=4,c++)Module.HEAPU8[d+c]=e[b];quircDecoded=!1;Module._xprocess();if(quircDecoded&&quircResult)return{success:!0,data:quircResult}}catch(d){}try{let d=zxing.decode(a);if(d)return{success:!0,data:uintToString(Uint8Array.from(d.flat()))}}catch(d){}return{success:!1}}
function showResult(a){a.success?qrResult.value=a.data:(qrResult.value="",window.alert(chrome.i18n.getMessage("scanNoResult")))}
function loadImage(a){let b;if(a)b=URL.createObjectURL(a);else if(b=inputURL.value.trim(),!b){window.alert(chrome.i18n.getMessage("scanEmptyURL"));return}let c=new Image;c.addEventListener("load",function(){canvas.width=c.width;canvas.height=c.height;ctx.drawImage(c,0,0,canvas.width,canvas.height);try{let d=ctx.getImageData(0,0,canvas.width,canvas.height),e=scanImage(d);showResult(e)}catch(d){qrResult.value="",a||requestPermission(b)}c.remove();a&&URL.revokeObjectURL(b)});c.addEventListener("error",
function(d){try{new URL(b)}catch(e){window.alert(chrome.i18n.getMessage("scanInvalidURL"));return}requestPermission(b);c.remove();a&&URL.revokeObjectURL(b)});b.startsWith("http://")||b.startsWith("https://")?chrome.permissions.contains({origins:[b]},function(d){d||(c.crossOrigin="anonymous");c.src=b}):c.src=b}function loadFile(){0<inputFile.files.length&&loadImage(inputFile.files[0])}
function drawLine(a,b,c){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineWidth=4;ctx.strokeStyle=c;ctx.stroke()}
class CamScan{static checkDevices(){void 0!==CamScan.videoInputCount&&0<CamScan.videoInputCount||(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices?navigator.mediaDevices.enumerateDevices().then(CamScan.checkVideoInput).catch(function(a){console.log(a.name+": "+a.message)}):console.log("enumerateDevices() not supported."))}static checkVideoInput(a){a=a.filter(c=>"videoinput"===c.kind&&c.deviceId);CamScan.videoInputCount=a.length;if(1<a.length){let c=document.createElement("select");
c.className="custom-select w-auto";c.style.maxWidth="17rem";var b=document.createElement("option");b.textContent=chrome.i18n.getMessage("scanDefaultCamera");b.value="default";c.appendChild(b);for(b=0;b<a.length;b++){let d=document.createElement("option");d.textContent=a[b].label;d.value=a[b].deviceId;c.appendChild(d)}camScanBtn.parentElement.appendChild(c);CamScan.camera=c}}static toggle(){cameraStream?CamScan.stop(!0):CamScan.start()}static start(){if(void 0!==navigator.mediaDevices){var a={facingMode:"environment"};
CamScan.camera&&"default"!=CamScan.camera.value&&(a={deviceId:CamScan.camera.value});navigator.mediaDevices.getUserMedia({video:a,audio:!1}).then(function(b){qrResult.value="";camScanBtn.textContent=chrome.i18n.getMessage("scanStopBtn");camScanBtn.classList.replace("btn-primary","btn-danger");canvas.classList.add("d-none");containerUrlinput.classList.add("d-none");containerFileinput.classList.add("d-none");previewVideo.classList.remove("d-none");CamScan.camera&&CamScan.camera.classList.add("d-none");
document.pictureInPictureEnabled&&pipBtn.classList.remove("d-none");cameraStream=b;previewVideo.srcObject=b;previewVideo.play();CamScan.rafId=requestAnimationFrame(CamScan.tick)}).catch(function(b){window.alert(chrome.i18n.getMessage("scanCameraError"));console.log("navigator.MediaDevices.getUserMedia error: ",b.message,b.name)})}}static stop(a){camScanBtn.textContent=chrome.i18n.getMessage("scanCamBtn");camScanBtn.classList.replace("btn-danger","btn-primary");canvas.classList.remove("d-none");containerUrlinput.classList.remove("d-none");
containerFileinput.classList.remove("d-none");previewVideo.classList.add("d-none");CamScan.camera&&CamScan.camera.classList.remove("d-none");cancelAnimationFrame(CamScan.rafId);cameraStream.getTracks().forEach(b=>b.stop());cameraStream=void 0;a&&ctx.clearRect(0,0,canvas.width,canvas.height);document.pictureInPictureEnabled&&(pipBtn.classList.add("d-none"),CamScan.closePip());CamScan.checkDevices()}static tick(){if(previewVideo.readyState===previewVideo.HAVE_ENOUGH_DATA){canvas.height=previewVideo.videoHeight;
canvas.width=previewVideo.videoWidth;ctx.drawImage(previewVideo,0,0,canvas.width,canvas.height);var a=ctx.getImageData(0,0,canvas.width,canvas.height);if((a=jsQR(a.data,a.width,a.height,{inversionAttempts:"dontInvert"}))&&a.data){showResult({success:!0,data:a.data});drawLine(a.location.topLeftCorner,a.location.topRightCorner,"#FF3B58");drawLine(a.location.topRightCorner,a.location.bottomRightCorner,"#FF3B58");drawLine(a.location.bottomRightCorner,a.location.bottomLeftCorner,"#FF3B58");drawLine(a.location.bottomLeftCorner,
a.location.topLeftCorner,"#FF3B58");CamScan.stop(!1);return}}CamScan.rafId=requestAnimationFrame(CamScan.tick)}static pip(){0!==previewVideo.readyState&&(document.pictureInPictureElement?document.exitPictureInPicture():previewVideo.requestPictureInPicture())}static closePip(){0!==previewVideo.readyState&&document.pictureInPictureElement&&document.exitPictureInPicture()}}
function copy(){const a=qrResult.value.trim();a&&navigator.clipboard.writeText(a).then(()=>{copiedTimeout&&(clearTimeout(copiedTimeout),copiedTimeout=null);copied.classList.replace("d-none","d-inline");copiedTimeout=setTimeout(()=>{copiedTimeout=null;copied.classList.replace("d-inline","d-none")},1E3)}).catch(b=>{console.log("Could not copy text: ",b)})}function openInTab(){const a=qrResult.value.trim();(a.startsWith("http://")||a.startsWith("https://"))&&chrome.tabs.create({url:a})}
function init(){initMsg();loadUrlBtn.addEventListener("click",b=>loadImage());inputFile.addEventListener("change",loadFile);camScanBtn.addEventListener("click",CamScan.toggle);pipBtn.addEventListener("click",CamScan.pip);copyBtn.addEventListener("click",copy);openBtn.addEventListener("click",openInTab);copyBtn.title=chrome.i18n.getMessage("scanCopy");openBtn.title=chrome.i18n.getMessage("scanOpen");let a=(new URL(location.href)).searchParams.get("url");a?(inputURL.value=a,loadImage()):(inputURL.value=
"img/qrcode-example.png",loadImage(),inputURL.value="");CamScan.checkDevices()}init();
